name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: cd C2_s21_stringplus-3/src && make 
    - name: make check
      run: cd C2_s21_stringplus-3/src && make check
    - name: make gcov_report
      run: cd src && make gcov_report
