name: Test Coveralls

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov
          gem install coveralls-lcov

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure for coverage
        run: |
          ./autogen.sh
          ./configure --enable-coverage

      - name: Build and run tests
        run: make test

      - name: Generate coverage report
        run: |
          lcov --compat-libtool --directory . --capture --output-file coverage.info

  coveralls:
    needs: [build-linux]
    runs-on: ubuntu-latest

    steps:
      - name: Upload coverage report to Coveralls
        run: coveralls-lcov coverage.info
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.YOUR_COVERALLS_REPO_TOKEN }}
