name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y check gcovr

    - uses: actions/checkout@v2

    - name: Build and test
      run: |
        cd C2_s21_stringplus-3/src
        make
        make test
        make gcov_report

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: gcov-report
        path: C2_s21_stringplus-3/src/gcov_report
