name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Install check
      run: sudo apt-get update && sudo apt-get install check
    - name: Install gcovr
      run: sudo apt-get install gcovr
    - uses: actions/checkout@v4
    - name: make
      run: cd C2_s21_stringplus-3/src && make 
    - name: make test
      run: cd C2_s21_stringplus-3/src && make test
    - name: make gcov_report
      run: cd C2_s21_stringplus-3/src && make gcov_report
    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: gcov-report
        path: C2_s21_stringplus-3/src/gcov_report